/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */



import javax.swing.UIManager;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.awt.Color;




/**
 *
 * @author nitesh.sharma
 */
public class LoginPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginPage.class.getName());

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        //center screen
   setLocationRelativeTo(null);
     //enter key login
     PasswordTF.addActionListener(e -> logInbtn.doClick());
     
     logInbtn.addActionListener(e -> {
    String username = userTF.getText();
    String password = new String(PasswordTF.getPassword());

    if(username.equals("admin") && password.equals("1234")) {

        // Show popup
        javax.swing.JOptionPane.showMessageDialog(this, "Successfully Login");

        // Disable login button
        logInbtn.setEnabled(false);

    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Invalid Credentials");
    }
});
    

    // Message center align
    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userTF = new javax.swing.JTextField();
        PasswordTF = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        clearbtn = new javax.swing.JButton();
        logInbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(java.awt.Color.lightGray);
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Username :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 40, 98, 27));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Password :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 100, 90, -1));

        userTF.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        userTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userTF.setToolTipText("JYFU");
        userTF.addActionListener(this::userTFActionPerformed);
        jPanel1.add(userTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 35, 145, 32));

        PasswordTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PasswordTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordTF.addActionListener(this::PasswordTFActionPerformed);
        jPanel1.add(PasswordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 97, 145, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 332, 264, -1));

        clearbtn.setBackground(new java.awt.Color(0, 255, 0));
        clearbtn.setText("Clear");
        clearbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clearbtn.setBorderPainted(false);
        clearbtn.addActionListener(this::clearbtnActionPerformed);
        jPanel1.add(clearbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 70, 30));

        logInbtn.setBackground(new java.awt.Color(0, 0, 204));
        logInbtn.setText("Log In");
        logInbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logInbtn.setBorderPainted(false);
        jPanel1.add(logInbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 70, 30));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOG IN PAGE");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 0, 153), null, new java.awt.Color(204, 0, 102)));
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTFActionPerformed
             
        // TODO add your handling code here:
    }//GEN-LAST:event_userTFActionPerformed

    private void PasswordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTFActionPerformed
         logInbtn.doClick(); // Enter press = login
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTFActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        // TODO add your handling code here:
        userTF.setText("");
        PasswordTF.setText("");
        jLabel4.setText("");
    }//GEN-LAST:event_clearbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordTF;
    private javax.swing.JButton clearbtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logInbtn;
    private javax.swing.JTextField userTF;
    // End of variables declaration//GEN-END:variables
}
